promotionPrompt=p=>window.confirm(`${PIECES[p.type].symbol}を成りますか？`);
function selectBoard(x,y){const p=state.board[y][x];state.selected={kind:"board",x,y};state.moves=boardMoves(p,x,y);state.message=`${symbol(p)}（${ATTRIBUTE_DATA[p.attr].label}属性）を選択中。`;state.tone="info";render()}function selectHand(i){const p=state.hand[HUMAN][i];if(!p)return;state.selected={kind:"hand",index:i};state.moves=dropMoves(p).map(m=>({...m,handIndex:i}));state.message=`持ち駒 ${symbol(p)}（${ATTRIBUTE_DATA[p.attr].label}属性）を選択中。`;render()}
function clickSquare(x,y){if(state.winner||state.aiThinking||state.turn!==HUMAN)return;const m=state.moves.find(v=>v.x===x&&v.y===y);if(m){if(m.kind==="board")Object.assign(m,{fromX:state.selected.x,fromY:state.selected.y});execute(m);return}const p=state.board[y][x];if(p&&p.color===HUMAN)selectBoard(x,y);else{state.selected=null;state.moves=[];state.message="自分の駒または持ち駒を選んでください。";render()}}
function renderBoard(){const el=document.getElementById("board");el.innerHTML="";state.board.forEach((r,y)=>r.forEach((p,x)=>{const b=document.createElement("button"),clash=clashAt(x,y);b.type="button";b.className=`square ${(x+y)%2?"dark":"light"}`;b.dataset.x=x;b.dataset.y=y;b.onclick=()=>clickSquare(x,y);if(state.selected?.kind==="board"&&state.selected.x===x&&state.selected.y===y)b.classList.add("selected");const m=state.moves.find(v=>v.x===x&&v.y===y);if(m)b.classList.add(m.result==="capture"?"capture-target":m.result==="retaliation"?"retaliation-target":m.result==="same"?"same-target":m.result==="support"?"support-target":"move-target");if(clash){const remaining=clash.expiresAt-state.ply;b.classList.add("clash-square");if(clash.kingCollision)b.classList.add("king-clash");b.disabled=true;b.title=`${clash.kingCollision?"王の":""}${ATTRIBUTE_DATA[clash.attr].label}属性衝突・残り${remaining}ターン`;b.innerHTML=`<span class="clash-icon">${attributeIcon(clash.attr)}</span><span class="clash-pieces">${clash.pieces.map(q=>symbol(q)).join("×")}</span><span class="clash-turns">${remaining}</span>`}else if(p){b.title=`${symbol(p)} / ${ATTRIBUTE_DATA[p.attr].label}属性${p.type==="king"?` / 弱属性被弾 ${p.weakHits}/2`:""}`;b.innerHTML=`<span class="piece ${p.color}"><span class="piece-symbol ${p.color===CPU?"flipped":""}">${symbol(p)}</span><span class="attr attr-${p.attr}">${attributeIcon(p.attr)}</span>${p.type==="king"&&p.weakHits?`<span class="king-damage">1/2</span>`:""}</span>`}el.appendChild(b)}))}
function handPieceHtml(p,c){return `<span class="hand-piece-icon ${c}"><span class="hand-piece-attr attr-${p.attr}">${attributeIcon(p.attr)}</span><span class="hand-piece-symbol ${c===CPU?"flipped":""}">${symbol(p)}</span></span>`}
function renderHand(c,listId,stockId){const list=document.getElementById(listId),stock=document.getElementById(stockId);list.innerHTML="";stock.innerHTML="";state.hand[c].forEach((p,i)=>{const label=`${symbol(p)}・${ATTRIBUTE_DATA[p.attr].label}属性`,content=handPieceHtml(p,c),li=document.createElement("li");li.innerHTML=content;li.title=label;li.setAttribute("aria-label",label);list.appendChild(li);const b=document.createElement("button");b.type="button";b.className=`stock-piece${c===HUMAN&&state.selected?.kind==="hand"&&state.selected.index===i?" selected-hand":""}`;b.innerHTML=content;b.title=label;b.setAttribute("aria-label",label);b.disabled=c!==HUMAN||state.turn!==HUMAN||state.aiThinking;b.dataset.handIndex=i;stock.appendChild(b)});if(!state.hand[c].length)stock.textContent="持ち駒なし"}
function renderLog(){const el=document.getElementById("move-log");el.innerHTML="";state.log.forEach(item=>{const li=document.createElement("li");li.textContent=item.text;el.appendChild(li)});if(!state.log.length){const li=document.createElement("li");li.className="log-empty";li.textContent="まだ着手はありません。";el.appendChild(li)}}
function render(){if(state.autoPlay)return;renderBoard();renderHand(CPU,"black-hand","cpu-stock");renderHand(HUMAN,"white-hand","human-stock");renderLog();document.getElementById("turn").textContent=state.winner?"対局終了":`手番: ${owner(state.turn)}`;const msg=document.getElementById("message");msg.textContent=state.message;msg.className=`message ${state.tone}`}
function bind(){document.getElementById("human-stock").addEventListener("click",e=>{const b=e.target.closest("[data-hand-index]");if(b)selectHand(+b.dataset.handIndex)});document.getElementById("reset").addEventListener("click",()=>{state=initialState();render()})}
async function bootstrap(){try{const r=await fetch("attributes.json",{cache:"no-store"});if(!r.ok)throw Error("属性設定を読み込めません");ATTRIBUTE_DATA=await r.json();state=initialState();bind();render()}catch(e){document.getElementById("message").textContent=`起動エラー: ${e.message}。HTTPサーバーから開いてください。`}}document.addEventListener("DOMContentLoaded",bootstrap);
