const BOARD_SIZE=9,HUMAN="white",CPU="black";let ATTRIBUTE_DATA,state,promotionPrompt=()=>true;
const PIECES={king:{symbol:"王",value:1e4},rook:{symbol:"飛",promoted:"龍",value:900},bishop:{symbol:"角",promoted:"馬",value:800},gold:{symbol:"金",value:600},silver:{symbol:"銀",promoted:"全",value:500},knight:{symbol:"桂",promoted:"圭",value:350},lance:{symbol:"香",promoted:"杏",value:300},pawn:{symbol:"歩",promoted:"と",value:100}};
const PROMOTABLE=new Set(["rook","bishop","silver","knight","lance","pawn"]),GOLD=[[0,1],[-1,1],[1,1],[-1,0],[1,0],[0,-1]];
const piece=(type,color)=>({type,color,attr:null,promoted:false,weakHits:0,boardSince:0}),forward=c=>c===HUMAN?-1:1,inside=(x,y)=>x>=0&&x<9&&y>=0&&y<9,enemy=c=>c===HUMAN?CPU:HUMAN,owner=c=>c===HUMAN?"あなた":"CPU";
const coord=(x,y)=>`${x+1}-${y+1}`;
function createBoard(){const b=Array.from({length:9},()=>Array(9).fill(null)),back=["lance","knight","silver","gold","king","gold","silver","knight","lance"];back.forEach((t,x)=>{b[0][x]=piece(t,CPU);b[8][x]=piece(t,HUMAN)});b[1][1]=piece("rook",CPU);b[1][7]=piece("bishop",CPU);b[7][1]=piece("bishop",HUMAN);b[7][7]=piece("rook",HUMAN);for(let x=0;x<9;x++){b[2][x]=piece("pawn",CPU);b[6][x]=piece("pawn",HUMAN)}return b}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function assignAttributes(b){const all=b.flat().filter(Boolean),kings=all.filter(p=>p.type==="king"),others=all.filter(p=>p.type!=="king"),keys=shuffle(Object.keys(ATTRIBUTE_DATA)),base=Math.floor(all.length/keys.length),extra=all.length%keys.length,targets=Object.fromEntries(keys.map((key,i)=>[key,base+(i<extra?1:0)])),kingAttr=shuffle(keys.filter(key=>targets[key]>=kings.length))[0],pool=[];kings.forEach(p=>p.attr=kingAttr);keys.forEach(key=>{for(let i=0;i<targets[key]-(key===kingAttr?kings.length:0);i++)pool.push(key)});shuffle(pool).forEach((attr,i)=>others[i].attr=attr)}
function initialState(){const board=createBoard();assignAttributes(board),s={board,hand:{[HUMAN]:[],[CPU]:[]},turn:HUMAN,selected:null,moves:[],clashes:[],log:[],ply:0,winner:null,aiThinking:false,autoPlay:false,history:[],message:"あなたの番です。駒または持ち駒を選んでください。",tone:"info"};s.history.push({key:positionKey(s),actor:null,gaveCheck:false});return s}
function pieceKey(p){return p?`${p.type},${p.color},${p.attr},${p.promoted?1:0},${p.weakHits||0},${p.boardSince??"-"}`:"-"}
function positionKey(s=state){const board=s.board.map(row=>row.map(pieceKey).join("/")).join("|"),hands=[HUMAN,CPU].map(c=>s.hand[c].map(pieceKey).sort().join("/")).join("|"),clashes=s.clashes.map(c=>`${c.x},${c.y},${c.attr},${c.expiresAt-s.ply},${c.attackerColor||"-"},${c.pieces.map(pieceKey).sort().join("+")}`).sort().join("|");return `${s.turn}#${board}#${hands}#${clashes}`}
function recordPosition(actor,gaveCheck){const entry={key:positionKey(),actor,gaveCheck};state.history.push(entry);const occurrences=[];state.history.forEach((item,i)=>{if(item.key===entry.key)occurrences.push(i)});if(occurrences.length<4)return null;const segment=state.history.slice(occurrences.at(-4)+1),checking=[HUMAN,CPU].find(c=>{const moves=segment.filter(item=>item.actor===c);return moves.length&&moves.every(item=>item.gaveCheck)});if(checking){state.winner=enemy(checking);return `${owner(checking)}の連続王手による千日手のため、${owner(state.winner)}の勝利です。`}state.winner="draw";return "同一局面が4回現れたため、千日手で引き分けです。"}
const combat=(a,d)=>a===d?"same":ATTRIBUTE_DATA[a].beats===d?"capture":"retaliation",symbol=p=>p.promoted&&PIECES[p.type].promoted?PIECES[p.type].promoted:PIECES[p.type].symbol,zone=(c,y)=>c===HUMAN?y<=2:y>=6;
function attributeIcon(attr){const data=ATTRIBUTE_DATA[attr];return data.iconType==="image"?`<img src="${data.icon}" alt="${data.label}">`:data.icon}
function clashAt(x,y){return state.clashes.find(c=>c.x===x&&c.y===y)}
const clashStartedAt=c=>c.startedAt??c.expiresAt-(c.kingCollision?5:7);
function supportClashAt(x,y,attr,p=null){return state.clashes.find(c=>ATTRIBUTE_DATA[attr].beats===c.attr&&c.support.some(s=>s.x===x&&s.y===y)&&(!p||(p.boardSince!=null&&p.boardSince<=clashStartedAt(c))))}
function deadEnd(p,y){const last=p.color===HUMAN?0:8,second=p.color===HUMAN?1:7;return(p.type==="pawn"||p.type==="lance")?y===last:p.type==="knight"&&(y===last||y===second)}
function rawMoves(p,x,y,b,clashes=state.clashes){const f=forward(p.color),out=[],blocked=(nx,ny)=>clashes.some(c=>c.x===nx&&c.y===ny);const step=(dx,dy)=>{const nx=x+dx,ny=y+dy;if(inside(nx,ny)&&!blocked(nx,ny)&&(!b[ny][nx]||b[ny][nx].color!==p.color))out.push({x:nx,y:ny})};const lines=dirs=>dirs.forEach(([dx,dy])=>{for(let n=1;n<9;n++){const nx=x+dx*n,ny=y+dy*n;if(!inside(nx,ny)||blocked(nx,ny))break;const target=b[ny][nx];if(!target)out.push({x:nx,y:ny});else{if(target.color!==p.color)out.push({x:nx,y:ny});break}}});
if(p.promoted&&["pawn","lance","knight","silver"].includes(p.type))GOLD.forEach(([dx,dy])=>step(dx,dy*f));else if(p.type==="king")[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]].forEach(d=>step(...d));else if(p.type==="gold")GOLD.forEach(([dx,dy])=>step(dx,dy*f));else if(p.type==="silver")[[0,1],[-1,1],[1,1],[-1,-1],[1,-1]].forEach(([dx,dy])=>step(dx,dy*f));else if(p.type==="knight")[[-1,2],[1,2]].forEach(([dx,dy])=>step(dx,dy*f));else if(p.type==="pawn")step(0,f);else if(p.type==="lance")lines([[0,f]]);else if(p.type==="rook"){lines([[0,-1],[0,1],[-1,0],[1,0]]);if(p.promoted)[[-1,-1],[1,-1],[-1,1],[1,1]].forEach(d=>step(...d))}else if(p.type==="bishop"){lines([[-1,-1],[1,-1],[-1,1],[1,1]]);if(p.promoted)[[0,-1],[0,1],[-1,0],[1,0]].forEach(d=>step(...d))}return out}
function kingState(color,board=state.board,clashes=state.clashes){for(let y=0;y<9;y++)for(let x=0;x<9;x++){const p=board[y][x];if(p&&p.color===color&&p.type==="king")return{piece:p,x,y,clash:null}}for(const clash of clashes){const p=clash.pieces.find(q=>q.color===color&&q.type==="king");if(p)return{piece:p,x:clash.x,y:clash.y,clash}}return null}
function kingThreatened(color,board=state.board,clashes=state.clashes){const king=kingState(color,board,clashes);if(!king)return true;if(king.clash)return false;for(let y=0;y<9;y++)for(let x=0;x<9;x++){const p=board[y][x];if(!p||p.color===color)continue;if(rawMoves(p,x,y,board,clashes).some(m=>m.x===king.x&&m.y===king.y)){const result=combat(p.attr,king.piece.attr);if(result==="capture"||(result==="retaliation"&&king.piece.weakHits>=1))return true}}return false}
function simulatedPosition(m,color){const board=state.board.map(row=>row.map(p=>p?{...p}:null)),clashes=state.clashes.map(c=>({...c,pieces:c.pieces.map(p=>({...p})),support:c.support.map(s=>({...s}))}));if(m.kind==="drop"){const p={...state.hand[color][m.handIndex],color,promoted:false};board[m.y][m.x]=p;return{board,clashes}}const p=board[m.fromY][m.fromX],target=board[m.y][m.x];board[m.fromY][m.fromX]=null;if(!target||m.result==="capture")board[m.y][m.x]=p;else if(m.result==="retaliation"){if(target.type!=="king")board[m.y][m.x]=null}else if(m.result==="same"){board[m.y][m.x]=null;clashes.push({x:m.x,y:m.y,attr:p.attr,pieces:[p,target],support:[]})}return{board,clashes}}
function legalForKing(m,color){const simulated=simulatedPosition(m,color);return!kingThreatened(color,simulated.board,simulated.clashes)}
function boardMoves(p,x,y){return rawMoves(p,x,y,state.board).map(d=>{const t=state.board[d.y][d.x],support=t?null:supportClashAt(d.x,d.y,p.attr),base=t?combat(p.attr,t.attr):support?(supportClashAt(d.x,d.y,p.attr,p)?"support":"blocked-support"):"move",result=t&&t.type==="king"&&base==="retaliation"&&t.weakHits>=1?"capture":base;return{...d,kind:"board",fromX:x,fromY:y,result}}).filter(m=>{const t=state.board[m.y][m.x];return m.result!=="blocked-support"&&!(p.type==="king"&&t?.type==="king"&&p.attr!==t.attr)&&legalForKing(m,p.color)})}
function pawnDropMate(m,p,color){const previous=state,simulated=simulatedPosition(m,color),hands={[HUMAN]:previous.hand[HUMAN].map(q=>({...q})),[CPU]:previous.hand[CPU].map(q=>({...q}))};hands[color].splice(m.handIndex,1);state={...previous,board:simulated.board,clashes:simulated.clashes,hand:hands,turn:enemy(color)};try{return kingThreatened(state.turn)&&allMoves(state.turn,true).length===0}finally{state=previous}}
function dropMoves(p,handIndex=state.hand[p.color].indexOf(p),skipPawnDropMate=false){const out=[];for(let y=0;y<9;y++)for(let x=0;x<9;x++)if(!state.board[y][x]&&!clashAt(x,y)&&!supportClashAt(x,y,p.attr)&&!deadEnd(p,y)){const nifu=p.type==="pawn"&&state.board.some(row=>{const q=row[x];return q&&q.color===p.color&&q.type==="pawn"&&!q.promoted}),m={x,y,kind:"drop",handIndex,result:"move"};if(!nifu&&legalForKing(m,p.color)&&!(p.type==="pawn"&&!skipPawnDropMate&&pawnDropMate(m,p,p.color)))out.push(m)}return out}
const mayPromote=(p,a,b)=>!p.promoted&&PROMOTABLE.has(p.type)&&(zone(p.color,a)||zone(p.color,b));function promoteChoice(p,a,b,cpu){if(!mayPromote(p,a,b))return false;if(deadEnd(p,b))return true;return cpu||promotionPrompt(p)}
function addHand(color,p){if(p.type!=="king")state.hand[color].push({...p,color,promoted:false,boardSince:null})}
function resolveBySupport(p,x,y){const clash=supportClashAt(x,y,p.attr,p);if(!clash)return null;const kings=clash.pieces.filter(q=>q.type==="king");if(kings.length===2){state.clashes=state.clashes.filter(c=>c!==clash);state.winner=p.color;return `${owner(p.color)}の強属性援軍が王同士の膠着を制し、勝利しました！`}if(kings.length===1){const king=kings[0],attacker=clash.pieces.find(q=>q.type!=="king");state.clashes=state.clashes.filter(c=>c!==clash);if(p.color===king.color){state.board[clash.y][clash.x]=king;addHand(king.color,attacker);return `${owner(king.color)}の援軍で王を救出し、${symbol(attacker)}を持ち駒にしました。`}state.board[clash.y][clash.x]=attacker;state.winner=p.color;return `${owner(p.color)}の強属性援軍により王が敗北しました。`}const winner=clash.pieces.find(q=>q.color===p.color),loser=clash.pieces.find(q=>q.color!==p.color);if(!winner||!loser)return null;state.board[clash.y][clash.x]=winner;addHand(p.color,loser);state.clashes=state.clashes.filter(c=>c!==clash);return `${owner(p.color)}の援軍で衝突を制しました。${symbol(loser)}を持ち駒にします。`}
function advanceClashes(){state.ply+=1;const expired=state.clashes.filter(c=>state.ply>=c.expiresAt),royal=expired.filter(c=>c.pieces.filter(p=>p.type==="king").length===2),kingWins=expired.filter(c=>c.pieces.filter(p=>p.type==="king").length===1),normal=expired.filter(c=>!c.pieces.some(p=>p.type==="king"));for(const clash of royal)state.winner=clash.attackerColor||clash.pieces[0].color;for(const clash of kingWins){const king=clash.pieces.find(p=>p.type==="king");state.board[clash.y][clash.x]=king}state.clashes=state.clashes.filter(c=>state.ply<c.expiresAt);return{normal:normal.length,king:kingWins.length,royal:royal.length}}
function addLog(text,color=state.turn){state.log.unshift({number:state.ply,color,text});state.log=state.log.slice(0,5)}
function finish(text,tone="info",logText=text){const actor=state.turn,expired=advanceClashes();state.board.flat().forEach(p=>{if(p&&p.boardSince==null)p.boardSince=state.ply});if(expired.normal)text+=` 衝突${expired.normal}件が6ターン経過し、両駒が消滅しました。`;if(expired.king)text+=` 王が4ターン耐え、同属性衝突に勝利しました。`;if(expired.royal)text+=` 王同士の膠着が4ターン続いたため、攻撃側の勝利です！`;addLog(logText);state.selected=null;state.moves=[];state.turn=enemy(state.turn);if(!state.winner){const checked=kingThreatened(state.turn);if(checked)text+=" 王手です。";const repetition=recordPosition(actor,checked);if(repetition)text=repetition}state.message=text;state.tone=state.winner?"success":tone;if(!state.winner)resolveNoLegalMoves();render();if(state.turn===CPU&&!state.winner&&!state.autoPlay){state.aiThinking=true;setTimeout(runAi,450)}}
function execute(m,cpu=false){if(m.kind==="drop"){const p=state.hand[state.turn].splice(m.handIndex,1)[0];p.color=state.turn;p.promoted=false;state.board[m.y][m.x]=p;const resolved=resolveBySupport(p,m.x,m.y),notation=`${symbol(p)} : 持ち駒 → ${coord(m.x,m.y)}${resolved?"（援軍勝利）":""}`;finish(resolved||`${owner(p.color)}が${symbol(p)}（${ATTRIBUTE_DATA[p.attr].label}属性）を打ちました。`,resolved?"success":"info",notation);return}const p=state.board[m.fromY][m.fromX],t=state.board[m.y][m.x],notation=()=>`${symbol(p)} : ${coord(m.fromX,m.fromY)} → ${coord(m.x,m.y)}`;if(t&&m.result==="same"){const kingCount=[p,t].filter(q=>q.type==="king").length,kingCollision=kingCount>0;state.board[m.fromY][m.fromX]=null;state.board[m.y][m.x]=null;state.clashes.push({x:m.x,y:m.y,attr:p.attr,pieces:[p,t],attackerColor:p.color,support:[{x:m.x,y:m.y-1},{x:m.x,y:m.y+1}].filter(s=>inside(s.x,s.y)),kingCollision,royalCollision:kingCount===2,expiresAt:state.ply+(kingCollision?5:7)});finish(`同じ${ATTRIBUTE_DATA[p.attr].label}属性が${kingCount===2?"王同士で衝突。4ターン以内に強属性援軍が来なければ攻撃側の勝利です。":kingCollision?"王と衝突。4ターン封鎖します。":"衝突。対象マスを6ターン封鎖します。"}`,"warning",notation());return}if(t&&m.result==="retaliation"){state.board[m.fromY][m.fromX]=null;if(t.type==="king"){if(t.weakHits>=1){state.board[m.y][m.x]=p;state.winner=p.color;state.ply+=1;state.message=`王が2回目の弱属性攻撃を受け、${owner(p.color)}が勝利しました！`;addLog(notation(),p.color);state.tone="success";state.selected=null;state.moves=[];render();return}t.weakHits+=1;addHand(t.color,p);finish(`${symbol(p)}は返り討ち。王は1回目の弱属性攻撃を防ぎました。`,"error",notation());return}state.board[m.y][m.x]=null;addHand(t.color,p);finish(`${symbol(p)}は返り討ち。両駒が盤上から消えました。`,"error",notation());return}state.board[m.fromY][m.fromX]=null;state.board[m.y][m.x]=p;if(t){if(t.type==="king"){state.winner=p.color;state.ply+=1;state.message=`${owner(p.color)}が王を取り、勝利しました！`;addLog(notation(),p.color);state.tone="success";state.selected=null;state.moves=[];render();return}addHand(p.color,t)}if(promoteChoice(p,m.fromY,m.y,cpu))p.promoted=true;const resolved=resolveBySupport(p,m.x,m.y);finish(resolved||(t?`${owner(p.color)}が有利属性で${symbol(t)}を取りました。`:`${owner(p.color)}が${symbol(p)}を移動しました。`),resolved||t?"success":"info",`${notation()}${resolved?"（援軍勝利）":""}`)}
function allMoves(c,skipPawnDropMate=false){const out=[];state.board.forEach((r,y)=>r.forEach((p,x)=>{if(p&&p.color===c)boardMoves(p,x,y).forEach(m=>out.push({...m,fromX:x,fromY:y}))}));state.hand[c].forEach((p,i)=>dropMoves(p,i,skipPawnDropMate).forEach(m=>out.push({...m,handIndex:i})));return out}
function passClashTurn(){const actor=state.turn,expired=advanceClashes();let text=`${owner(actor)}は王が衝突中で合法手がないためパスしました。`;if(expired.king)text+=" 王が4ターン耐え、衝突に勝利しました。";if(expired.royal)text+=" 王同士の膠着期限により攻撃側が勝利しました。";addLog("パス",actor);state.turn=enemy(actor);if(!state.winner){const checked=kingThreatened(state.turn),repetition=recordPosition(actor,checked);if(repetition)text=repetition}state.message=text;state.tone=state.winner?"success":"warning";if(!state.winner)resolveNoLegalMoves();render();if(state.turn===CPU&&!state.winner&&!state.autoPlay){state.aiThinking=true;setTimeout(runAi,450)}return true}
function resolveNoLegalMoves(){if(state.winner||allMoves(state.turn).length)return false;if(kingState(state.turn)?.clash)return passClashTurn();const checked=kingThreatened(state.turn);state.winner=enemy(state.turn);state.aiThinking=false;state.message=checked?`${owner(state.turn)}は王手を回避できません。${owner(state.winner)}の勝利です。`:`${owner(state.turn)}に合法手がありません。${owner(state.winner)}の勝利です。`;state.tone="success";return true}
function scoreMove(m,c){const t=state.board[m.y][m.x],att=m.kind==="board"&&state.board[m.fromY][m.fromX],moving=att||(m.kind==="drop"&&state.hand[c][m.handIndex]);let s=Math.random()*8;if(t&&m.result==="capture")s+=PIECES[t.type].value+(t.type==="king"?5e4:300);if(m.result==="retaliation"&&att)s-=PIECES[att.type].value+1000;if(m.result==="same")s-=2000;if(m.result==="support")s+=4000;if(att)s+=(c===CPU?m.y-m.fromY:m.fromY-m.y)*12;return s}
function chooseAiMove(c=state.turn){return allMoves(c).map(m=>({m,s:scoreMove(m,c)})).sort((a,b)=>b.s-a.s)[0]?.m||null}
function runAi(){if(state.winner||state.turn!==CPU)return;const move=chooseAiMove(CPU);if(!move){resolveNoLegalMoves();render();return}state.aiThinking=false;execute(move,true)}
function runSelfPlayGames(count=100,maxPlies=600){const original=state,results={games:count,white:0,black:0,draw:0,maxPly:0,stalled:0,errors:[]};for(let game=0;game<count;game++){try{state=initialState();state.autoPlay=true;while(!state.winner&&state.ply<maxPlies){const move=chooseAiMove(state.turn);if(move)execute(move,true);else resolveNoLegalMoves()}if(!state.winner){state.winner="draw";results.stalled++}results[state.winner]++;results.maxPly=Math.max(results.maxPly,state.ply)}catch(error){results.errors.push({game:game+1,message:error.message})}}state=original;render();return results}
